const mlbTeams = new Map([
    ['ARI', { name: 'Arizona Diamondbacks', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/ari.png' }],
    ['ATL', { name: 'Atlanta Braves', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/atl.png' }],
    ['BAL', { name: 'Baltimore Orioles', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/bal.png' }],
    ['BOS', { name: 'Boston Red Sox', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/bos.png' }],
    ['CHC', { name: 'Chicago Cubs', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/chc.png' }],
    ['CWS', { name: 'Chicago White Sox', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/cws.png' }],
    ['CIN', { name: 'Cincinnati Reds', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/cin.png' }],
    ['CLE', { name: 'Cleveland Guardians', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/cle.png' }],
    ['COL', { name: 'Colorado Rockies', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/col.png' }],
    ['DET', { name: 'Detroit Tigers', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/det.png' }],
    ['HOU', { name: 'Houston Astros', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/hou.png' }],
    ['KC', { name: 'Kansas City Royals', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/kc.png' }],
    ['LAA', { name: 'Los Angeles Angels', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/laa.png' }],
    ['LAD', { name: 'Los Angeles Dodgers', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/lad.png' }],
    ['MIA', { name: 'Miami Marlins', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/mia.png' }],
    ['MIL', { name: 'Milwaukee Brewers', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/mil.png' }],
    ['MIN', { name: 'Minnesota Twins', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/min.png' }],
    ['NYM', { name: 'New York Mets', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/nym.png' }],
    ['NYY', { name: 'New York Yankees', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/nyy.png' }],
    ['OAK', { name: 'Oakland Athletics', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/oak.png' }],
    ['PHI', { name: 'Philadelphia Phillies', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/phi.png' }],
    ['PIT', { name: 'Pittsburgh Pirates', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/pit.png' }],
    ['SD', { name: 'San Diego Padres', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/sd.png' }],
    ['SF', { name: 'San Francisco Giants', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/sf.png' }],
    ['SEA', { name: 'Seattle Mariners', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/sea.png' }],
    ['STL', { name: 'St. Louis Cardinals', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/stl.png' }],
    ['TB', { name: 'Tampa Bay Rays', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/tb.png' }],
    ['TEX', { name: 'Texas Rangers', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/tex.png' }],
    ['TOR', { name: 'Toronto Blue Jays', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/tor.png' }],
    ['WSH', { name: 'Washington Nationals', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/wsh.png' }],
    ['AL', {name: 'American League All-Stars', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/al.png'}],
    ['NL', {name: 'National League All-Stars', logo: 'https://a.espncdn.com/i/teamlogos/mlb/500/nl.png'}]
]);

export default mlbTeams;